export enum AppPermissions {
  CREATE_USER = "CREATE_USER",
  READ_USER = "READ_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",

  CREATE_PROPERTY = "CREATE_PROPERTY",
  READ_PROPERTY = "READ_PROPERTY",
  UPDATE_PROPERTY = "UPDATE_PROPERTY",
  DELETE_PROPERTY = "DELETE_PROPERTY",
}
